// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: messages.proto

package media

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetReviewPresignedUrlRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetReviewPresignedUrlRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReviewPresignedUrlRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetReviewPresignedUrlRequestMultiError, or nil if none found.
func (m *GetReviewPresignedUrlRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReviewPresignedUrlRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ObjectName

	// no validation rules for ReviewId

	if len(errors) > 0 {
		return GetReviewPresignedUrlRequestMultiError(errors)
	}

	return nil
}

// GetReviewPresignedUrlRequestMultiError is an error wrapping multiple
// validation errors returned by GetReviewPresignedUrlRequest.ValidateAll() if
// the designated constraints aren't met.
type GetReviewPresignedUrlRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReviewPresignedUrlRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReviewPresignedUrlRequestMultiError) AllErrors() []error { return m }

// GetReviewPresignedUrlRequestValidationError is the validation error returned
// by GetReviewPresignedUrlRequest.Validate if the designated constraints
// aren't met.
type GetReviewPresignedUrlRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReviewPresignedUrlRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReviewPresignedUrlRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReviewPresignedUrlRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReviewPresignedUrlRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReviewPresignedUrlRequestValidationError) ErrorName() string {
	return "GetReviewPresignedUrlRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetReviewPresignedUrlRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReviewPresignedUrlRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReviewPresignedUrlRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReviewPresignedUrlRequestValidationError{}

// Validate checks the field values on GetReviewPresignedUrlResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetReviewPresignedUrlResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReviewPresignedUrlResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetReviewPresignedUrlResponseMultiError, or nil if none found.
func (m *GetReviewPresignedUrlResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReviewPresignedUrlResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PresignedUrl

	// no validation rules for ObjectKey

	if len(errors) > 0 {
		return GetReviewPresignedUrlResponseMultiError(errors)
	}

	return nil
}

// GetReviewPresignedUrlResponseMultiError is an error wrapping multiple
// validation errors returned by GetReviewPresignedUrlResponse.ValidateAll()
// if the designated constraints aren't met.
type GetReviewPresignedUrlResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReviewPresignedUrlResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReviewPresignedUrlResponseMultiError) AllErrors() []error { return m }

// GetReviewPresignedUrlResponseValidationError is the validation error
// returned by GetReviewPresignedUrlResponse.Validate if the designated
// constraints aren't met.
type GetReviewPresignedUrlResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReviewPresignedUrlResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReviewPresignedUrlResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReviewPresignedUrlResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReviewPresignedUrlResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReviewPresignedUrlResponseValidationError) ErrorName() string {
	return "GetReviewPresignedUrlResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetReviewPresignedUrlResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReviewPresignedUrlResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReviewPresignedUrlResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReviewPresignedUrlResponseValidationError{}
