// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: service.proto

package media

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x120github.com.M1steryO.RelocatorEvents.media.api.v1\x1a\x0emessages.proto\x1a\x1cgoogle/api/annotations.proto2\xdc\x01\n" +
	"\fMediaService\x12\xcb\x01\n" +
	"\x15GetReviewPresignedUrl\x12N.github.com.M1steryO.RelocatorEvents.media.api.v1.GetReviewPresignedUrlRequest\x1aO.github.com.M1steryO.RelocatorEvents.media.api.v1.GetReviewPresignedUrlResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/media/v1B\x19Z\x17/pkg/api/media/v1;mediab\x06proto3"

var file_service_proto_goTypes = []any{
	(*GetReviewPresignedUrlRequest)(nil),  // 0: github.com.M1steryO.RelocatorEvents.media.api.v1.GetReviewPresignedUrlRequest
	(*GetReviewPresignedUrlResponse)(nil), // 1: github.com.M1steryO.RelocatorEvents.media.api.v1.GetReviewPresignedUrlResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: github.com.M1steryO.RelocatorEvents.media.api.v1.MediaService.GetReviewPresignedUrl:input_type -> github.com.M1steryO.RelocatorEvents.media.api.v1.GetReviewPresignedUrlRequest
	1, // 1: github.com.M1steryO.RelocatorEvents.media.api.v1.MediaService.GetReviewPresignedUrl:output_type -> github.com.M1steryO.RelocatorEvents.media.api.v1.GetReviewPresignedUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
