// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: events.proto

package events_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Event_V1_GetEvent_FullMethodName   = "/events_v1.Event_V1/GetEvent"
	Event_V1_ListEvents_FullMethodName = "/events_v1.Event_V1/ListEvents"
)

// Event_V1Client is the client API for Event_V1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Event_V1Client interface {
	GetEvent(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
}

type event_V1Client struct {
	cc grpc.ClientConnInterface
}

func NewEvent_V1Client(cc grpc.ClientConnInterface) Event_V1Client {
	return &event_V1Client{cc}
}

func (c *event_V1Client) GetEvent(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Event_V1_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *event_V1Client) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, Event_V1_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Event_V1Server is the server API for Event_V1 service.
// All implementations must embed UnimplementedEvent_V1Server
// for forward compatibility.
type Event_V1Server interface {
	GetEvent(context.Context, *GetRequest) (*GetResponse, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	mustEmbedUnimplementedEvent_V1Server()
}

// UnimplementedEvent_V1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEvent_V1Server struct{}

func (UnimplementedEvent_V1Server) GetEvent(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEvent_V1Server) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEvent_V1Server) mustEmbedUnimplementedEvent_V1Server() {}
func (UnimplementedEvent_V1Server) testEmbeddedByValue()                  {}

// UnsafeEvent_V1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Event_V1Server will
// result in compilation errors.
type UnsafeEvent_V1Server interface {
	mustEmbedUnimplementedEvent_V1Server()
}

func RegisterEvent_V1Server(s grpc.ServiceRegistrar, srv Event_V1Server) {
	// If the following call pancis, it indicates UnimplementedEvent_V1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Event_V1_ServiceDesc, srv)
}

func _Event_V1_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Event_V1Server).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_V1_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Event_V1Server).GetEvent(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_V1_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Event_V1Server).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_V1_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Event_V1Server).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Event_V1_ServiceDesc is the grpc.ServiceDesc for Event_V1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Event_V1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "events_v1.Event_V1",
	HandlerType: (*Event_V1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvent",
			Handler:    _Event_V1_GetEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _Event_V1_ListEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events.proto",
}
