// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: events.proto

package events_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EVENT_TYPE int32

const (
	EVENT_TYPE_offline EVENT_TYPE = 0
	EVENT_TYPE_online  EVENT_TYPE = 1
)

// Enum value maps for EVENT_TYPE.
var (
	EVENT_TYPE_name = map[int32]string{
		0: "offline",
		1: "online",
	}
	EVENT_TYPE_value = map[string]int32{
		"offline": 0,
		"online":  1,
	}
)

func (x EVENT_TYPE) Enum() *EVENT_TYPE {
	p := new(EVENT_TYPE)
	*p = x
	return p
}

func (x EVENT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EVENT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (EVENT_TYPE) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x EVENT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EVENT_TYPE.Descriptor instead.
func (EVENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventAddress struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	VenueName     *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=venue_name,proto3" json:"venue_name,omitempty"`
	FullAddress   string                  `protobuf:"bytes,2,opt,name=full_address,json=fullAddress,proto3" json:"full_address,omitempty"`
	Country       string                  `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	City          string                  `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District      *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	PostalCode    *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=postal_code,proto3" json:"postal_code,omitempty"`
	Latitude      *wrapperspb.FloatValue  `protobuf:"bytes,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     *wrapperspb.FloatValue  `protobuf:"bytes,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAddress) Reset() {
	*x = EventAddress{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAddress) ProtoMessage() {}

func (x *EventAddress) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAddress.ProtoReflect.Descriptor instead.
func (*EventAddress) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventAddress) GetVenueName() *wrapperspb.StringValue {
	if x != nil {
		return x.VenueName
	}
	return nil
}

func (x *EventAddress) GetFullAddress() string {
	if x != nil {
		return x.FullAddress
	}
	return ""
}

func (x *EventAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *EventAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EventAddress) GetDistrict() *wrapperspb.StringValue {
	if x != nil {
		return x.District
	}
	return nil
}

func (x *EventAddress) GetPostalCode() *wrapperspb.StringValue {
	if x != nil {
		return x.PostalCode
	}
	return nil
}

func (x *EventAddress) GetLatitude() *wrapperspb.FloatValue {
	if x != nil {
		return x.Latitude
	}
	return nil
}

func (x *EventAddress) GetLongitude() *wrapperspb.FloatValue {
	if x != nil {
		return x.Longitude
	}
	return nil
}

type Event struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Link           string                  `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Rating         *wrapperspb.FloatValue  `protobuf:"bytes,5,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewsCount   *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=reviews_count,proto3" json:"reviews_count,omitempty"`
	RatingsCount   *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=ratings_count,proto3" json:"ratings_count,omitempty"`
	MinAge         *wrapperspb.Int32Value  `protobuf:"bytes,8,opt,name=min_age,proto3" json:"min_age,omitempty"`
	SeatsAvailable *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=seats_available,proto3" json:"seats_available,omitempty"`
	EventType      EVENT_TYPE              `protobuf:"varint,10,opt,name=eventType,json=event_type,proto3,enum=events_v1.EVENT_TYPE" json:"eventType,omitempty"`
	MinPrice       *wrapperspb.Int32Value  `protobuf:"bytes,11,opt,name=min_price,proto3" json:"min_price,omitempty"`
	StartsAt       *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=starts_at,proto3" json:"starts_at,omitempty"`
	ImageUrl       *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=image_url,proto3" json:"image_url,omitempty"`
	Address        *EventAddress           `protobuf:"bytes,14,opt,name=address,proto3,oneof" json:"address,omitempty"`
	CreatedAt      *timestamppb.Timestamp  `protobuf:"bytes,15,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Currency       *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Event) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Event) GetRating() *wrapperspb.FloatValue {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *Event) GetReviewsCount() *wrapperspb.Int32Value {
	if x != nil {
		return x.ReviewsCount
	}
	return nil
}

func (x *Event) GetRatingsCount() *wrapperspb.Int32Value {
	if x != nil {
		return x.RatingsCount
	}
	return nil
}

func (x *Event) GetMinAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinAge
	}
	return nil
}

func (x *Event) GetSeatsAvailable() *wrapperspb.Int32Value {
	if x != nil {
		return x.SeatsAvailable
	}
	return nil
}

func (x *Event) GetEventType() EVENT_TYPE {
	if x != nil {
		return x.EventType
	}
	return EVENT_TYPE_offline
}

func (x *Event) GetMinPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinPrice
	}
	return nil
}

func (x *Event) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Event) GetImageUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

func (x *Event) GetAddress() *EventAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Event) GetCurrency() *wrapperspb.StringValue {
	if x != nil {
		return x.Currency
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Q             *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Sort          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	City          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	District      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	MinPrice      *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=min_price,proto3" json:"min_price,omitempty"`
	MaxPrice      *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=max_price,proto3" json:"max_price,omitempty"`
	EventDate     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=event_date,proto3" json:"event_date,omitempty"`
	EventType     *EVENT_TYPE             `protobuf:"varint,8,opt,name=event_type,proto3,enum=events_v1.EVENT_TYPE,oneof" json:"event_type,omitempty"`
	Category      []string                `protobuf:"bytes,9,rep,name=category,proto3" json:"category,omitempty"`
	Limit         *wrapperspb.Int64Value  `protobuf:"bytes,10,opt,name=limit,proto3" json:"limit,omitempty"`
	LastId        *wrapperspb.Int64Value  `protobuf:"bytes,11,opt,name=last_id,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsRequest) GetQ() *wrapperspb.StringValue {
	if x != nil {
		return x.Q
	}
	return nil
}

func (x *ListEventsRequest) GetSort() *wrapperspb.StringValue {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListEventsRequest) GetCity() *wrapperspb.StringValue {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *ListEventsRequest) GetDistrict() *wrapperspb.StringValue {
	if x != nil {
		return x.District
	}
	return nil
}

func (x *ListEventsRequest) GetMinPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinPrice
	}
	return nil
}

func (x *ListEventsRequest) GetMaxPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxPrice
	}
	return nil
}

func (x *ListEventsRequest) GetEventDate() *wrapperspb.StringValue {
	if x != nil {
		return x.EventDate
	}
	return nil
}

func (x *ListEventsRequest) GetEventType() EVENT_TYPE {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return EVENT_TYPE_offline
}

func (x *ListEventsRequest) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ListEventsRequest) GetLimit() *wrapperspb.Int64Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *ListEventsRequest) GetLastId() *wrapperspb.Int64Value {
	if x != nil {
		return x.LastId
	}
	return nil
}

type EventCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCategory) Reset() {
	*x = EventCategory{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCategory) ProtoMessage() {}

func (x *EventCategory) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCategory.ProtoReflect.Descriptor instead.
func (*EventCategory) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *EventCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventCategory) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type FiltersValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPrice      *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=min_price,proto3" json:"min_price,omitempty"`
	MaxPrice      *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=max_price,proto3" json:"max_price,omitempty"`
	Cities        []string               `protobuf:"bytes,3,rep,name=cities,proto3" json:"cities,omitempty"`
	Categories    []*EventCategory       `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiltersValues) Reset() {
	*x = FiltersValues{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiltersValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiltersValues) ProtoMessage() {}

func (x *FiltersValues) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiltersValues.ProtoReflect.Descriptor instead.
func (*FiltersValues) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *FiltersValues) GetMinPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinPrice
	}
	return nil
}

func (x *FiltersValues) GetMaxPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxPrice
	}
	return nil
}

func (x *FiltersValues) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *FiltersValues) GetCategories() []*EventCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Event               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Filters       *FiltersValues         `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsResponse) GetData() []*Event {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListEventsResponse) GetFilters() *FiltersValues {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\tevents_v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\vGetResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.events_v1.EventR\x05event\"\x8b\x03\n" +
	"\fEventAddress\x12<\n" +
	"\n" +
	"venue_name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"venue_name\x12!\n" +
	"\ffull_address\x18\x02 \x01(\tR\vfullAddress\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x128\n" +
	"\bdistrict\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\bdistrict\x12>\n" +
	"\vpostal_code\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\vpostal_code\x127\n" +
	"\blatitude\x18\b \x01(\v2\x1b.google.protobuf.FloatValueR\blatitude\x129\n" +
	"\tlongitude\x18\t \x01(\v2\x1b.google.protobuf.FloatValueR\tlongitude\"\x97\a\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x123\n" +
	"\x06rating\x18\x05 \x01(\v2\x1b.google.protobuf.FloatValueR\x06rating\x12A\n" +
	"\rreviews_count\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\rreviews_count\x12A\n" +
	"\rratings_count\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\rratings_count\x125\n" +
	"\amin_age\x18\b \x01(\v2\x1b.google.protobuf.Int32ValueR\amin_age\x12E\n" +
	"\x0fseats_available\x18\t \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fseats_available\x124\n" +
	"\teventType\x18\n" +
	" \x01(\x0e2\x15.events_v1.EVENT_TYPER\n" +
	"event_type\x129\n" +
	"\tmin_price\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\tmin_price\x128\n" +
	"\tstarts_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstarts_at\x12:\n" +
	"\timage_url\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\timage_url\x126\n" +
	"\aaddress\x18\x0e \x01(\v2\x17.events_v1.EventAddressH\x00R\aaddress\x88\x01\x01\x12:\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x128\n" +
	"\bcurrency\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\bcurrencyB\n" +
	"\n" +
	"\b_address\"\xe2\x04\n" +
	"\x11ListEventsRequest\x12*\n" +
	"\x01q\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x01q\x120\n" +
	"\x04sort\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04sort\x120\n" +
	"\x04city\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04city\x128\n" +
	"\bdistrict\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\bdistrict\x129\n" +
	"\tmin_price\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\tmin_price\x129\n" +
	"\tmax_price\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\tmax_price\x12<\n" +
	"\n" +
	"event_date\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"event_date\x12:\n" +
	"\n" +
	"event_type\x18\b \x01(\x0e2\x15.events_v1.EVENT_TYPEH\x00R\n" +
	"event_type\x88\x01\x01\x12\x1a\n" +
	"\bcategory\x18\t \x03(\tR\bcategory\x121\n" +
	"\x05limit\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int64ValueR\x05limit\x125\n" +
	"\alast_id\x18\v \x01(\v2\x1b.google.protobuf.Int64ValueR\alast_idB\r\n" +
	"\v_event_type\"9\n" +
	"\rEventCategory\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xd7\x01\n" +
	"\rFiltersValues\x129\n" +
	"\tmin_price\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\tmin_price\x129\n" +
	"\tmax_price\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\tmax_price\x12\x16\n" +
	"\x06cities\x18\x03 \x03(\tR\x06cities\x128\n" +
	"\n" +
	"categories\x18\x04 \x03(\v2\x18.events_v1.EventCategoryR\n" +
	"categories\"n\n" +
	"\x12ListEventsResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.events_v1.EventR\x04data\x122\n" +
	"\afilters\x18\x02 \x01(\v2\x18.events_v1.FiltersValuesR\afilters*%\n" +
	"\n" +
	"EVENT_TYPE\x12\v\n" +
	"\aoffline\x10\x00\x12\n" +
	"\n" +
	"\x06online\x10\x012\xc2\x01\n" +
	"\bEvent_V1\x12R\n" +
	"\bGetEvent\x12\x15.events_v1.GetRequest\x1a\x16.events_v1.GetResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/events/v1/{id}\x12b\n" +
	"\n" +
	"ListEvents\x12\x1c.events_v1.ListEventsRequest\x1a\x1d.events_v1.ListEventsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/events/v1/listB?Z=GolandProjects/RelocatorEvents/events/pkg/events_v1;events_v1b\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_events_proto_goTypes = []any{
	(EVENT_TYPE)(0),                // 0: events_v1.EVENT_TYPE
	(*GetRequest)(nil),             // 1: events_v1.GetRequest
	(*GetResponse)(nil),            // 2: events_v1.GetResponse
	(*EventAddress)(nil),           // 3: events_v1.EventAddress
	(*Event)(nil),                  // 4: events_v1.Event
	(*ListEventsRequest)(nil),      // 5: events_v1.ListEventsRequest
	(*EventCategory)(nil),          // 6: events_v1.EventCategory
	(*FiltersValues)(nil),          // 7: events_v1.FiltersValues
	(*ListEventsResponse)(nil),     // 8: events_v1.ListEventsResponse
	(*wrapperspb.StringValue)(nil), // 9: google.protobuf.StringValue
	(*wrapperspb.FloatValue)(nil),  // 10: google.protobuf.FloatValue
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil),  // 13: google.protobuf.Int64Value
}
var file_events_proto_depIdxs = []int32{
	4,  // 0: events_v1.GetResponse.event:type_name -> events_v1.Event
	9,  // 1: events_v1.EventAddress.venue_name:type_name -> google.protobuf.StringValue
	9,  // 2: events_v1.EventAddress.district:type_name -> google.protobuf.StringValue
	9,  // 3: events_v1.EventAddress.postal_code:type_name -> google.protobuf.StringValue
	10, // 4: events_v1.EventAddress.latitude:type_name -> google.protobuf.FloatValue
	10, // 5: events_v1.EventAddress.longitude:type_name -> google.protobuf.FloatValue
	9,  // 6: events_v1.Event.description:type_name -> google.protobuf.StringValue
	10, // 7: events_v1.Event.rating:type_name -> google.protobuf.FloatValue
	11, // 8: events_v1.Event.reviews_count:type_name -> google.protobuf.Int32Value
	11, // 9: events_v1.Event.ratings_count:type_name -> google.protobuf.Int32Value
	11, // 10: events_v1.Event.min_age:type_name -> google.protobuf.Int32Value
	11, // 11: events_v1.Event.seats_available:type_name -> google.protobuf.Int32Value
	0,  // 12: events_v1.Event.eventType:type_name -> events_v1.EVENT_TYPE
	11, // 13: events_v1.Event.min_price:type_name -> google.protobuf.Int32Value
	12, // 14: events_v1.Event.starts_at:type_name -> google.protobuf.Timestamp
	9,  // 15: events_v1.Event.image_url:type_name -> google.protobuf.StringValue
	3,  // 16: events_v1.Event.address:type_name -> events_v1.EventAddress
	12, // 17: events_v1.Event.created_at:type_name -> google.protobuf.Timestamp
	12, // 18: events_v1.Event.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 19: events_v1.Event.currency:type_name -> google.protobuf.StringValue
	9,  // 20: events_v1.ListEventsRequest.q:type_name -> google.protobuf.StringValue
	9,  // 21: events_v1.ListEventsRequest.sort:type_name -> google.protobuf.StringValue
	9,  // 22: events_v1.ListEventsRequest.city:type_name -> google.protobuf.StringValue
	9,  // 23: events_v1.ListEventsRequest.district:type_name -> google.protobuf.StringValue
	11, // 24: events_v1.ListEventsRequest.min_price:type_name -> google.protobuf.Int32Value
	11, // 25: events_v1.ListEventsRequest.max_price:type_name -> google.protobuf.Int32Value
	9,  // 26: events_v1.ListEventsRequest.event_date:type_name -> google.protobuf.StringValue
	0,  // 27: events_v1.ListEventsRequest.event_type:type_name -> events_v1.EVENT_TYPE
	13, // 28: events_v1.ListEventsRequest.limit:type_name -> google.protobuf.Int64Value
	13, // 29: events_v1.ListEventsRequest.last_id:type_name -> google.protobuf.Int64Value
	11, // 30: events_v1.FiltersValues.min_price:type_name -> google.protobuf.Int32Value
	11, // 31: events_v1.FiltersValues.max_price:type_name -> google.protobuf.Int32Value
	6,  // 32: events_v1.FiltersValues.categories:type_name -> events_v1.EventCategory
	4,  // 33: events_v1.ListEventsResponse.data:type_name -> events_v1.Event
	7,  // 34: events_v1.ListEventsResponse.filters:type_name -> events_v1.FiltersValues
	1,  // 35: events_v1.Event_V1.GetEvent:input_type -> events_v1.GetRequest
	5,  // 36: events_v1.Event_V1.ListEvents:input_type -> events_v1.ListEventsRequest
	2,  // 37: events_v1.Event_V1.GetEvent:output_type -> events_v1.GetResponse
	8,  // 38: events_v1.Event_V1.ListEvents:output_type -> events_v1.ListEventsResponse
	37, // [37:39] is the sub-list for method output_type
	35, // [35:37] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_events_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
