// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: favourites.proto

package favourites_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FavouritesService_ListFavourites_FullMethodName   = "/favourites_v1.FavouritesService/ListFavourites"
	FavouritesService_AddFavourites_FullMethodName    = "/favourites_v1.FavouritesService/AddFavourites"
	FavouritesService_DeleteFavourites_FullMethodName = "/favourites_v1.FavouritesService/DeleteFavourites"
)

// FavouritesServiceClient is the client API for FavouritesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavouritesServiceClient interface {
	ListFavourites(ctx context.Context, in *ListFavouritesRequest, opts ...grpc.CallOption) (*ListFavouritesResponse, error)
	AddFavourites(ctx context.Context, in *AddFavouritesRequest, opts ...grpc.CallOption) (*AddFavouritesResponse, error)
	DeleteFavourites(ctx context.Context, in *DeleteFavouritesRequest, opts ...grpc.CallOption) (*DeleteFavouritesResponse, error)
}

type favouritesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavouritesServiceClient(cc grpc.ClientConnInterface) FavouritesServiceClient {
	return &favouritesServiceClient{cc}
}

func (c *favouritesServiceClient) ListFavourites(ctx context.Context, in *ListFavouritesRequest, opts ...grpc.CallOption) (*ListFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFavouritesResponse)
	err := c.cc.Invoke(ctx, FavouritesService_ListFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favouritesServiceClient) AddFavourites(ctx context.Context, in *AddFavouritesRequest, opts ...grpc.CallOption) (*AddFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFavouritesResponse)
	err := c.cc.Invoke(ctx, FavouritesService_AddFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favouritesServiceClient) DeleteFavourites(ctx context.Context, in *DeleteFavouritesRequest, opts ...grpc.CallOption) (*DeleteFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavouritesResponse)
	err := c.cc.Invoke(ctx, FavouritesService_DeleteFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavouritesServiceServer is the server API for FavouritesService service.
// All implementations must embed UnimplementedFavouritesServiceServer
// for forward compatibility.
type FavouritesServiceServer interface {
	ListFavourites(context.Context, *ListFavouritesRequest) (*ListFavouritesResponse, error)
	AddFavourites(context.Context, *AddFavouritesRequest) (*AddFavouritesResponse, error)
	DeleteFavourites(context.Context, *DeleteFavouritesRequest) (*DeleteFavouritesResponse, error)
	mustEmbedUnimplementedFavouritesServiceServer()
}

// UnimplementedFavouritesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFavouritesServiceServer struct{}

func (UnimplementedFavouritesServiceServer) ListFavourites(context.Context, *ListFavouritesRequest) (*ListFavouritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFavourites not implemented")
}
func (UnimplementedFavouritesServiceServer) AddFavourites(context.Context, *AddFavouritesRequest) (*AddFavouritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFavourites not implemented")
}
func (UnimplementedFavouritesServiceServer) DeleteFavourites(context.Context, *DeleteFavouritesRequest) (*DeleteFavouritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFavourites not implemented")
}
func (UnimplementedFavouritesServiceServer) mustEmbedUnimplementedFavouritesServiceServer() {}
func (UnimplementedFavouritesServiceServer) testEmbeddedByValue()                           {}

// UnsafeFavouritesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavouritesServiceServer will
// result in compilation errors.
type UnsafeFavouritesServiceServer interface {
	mustEmbedUnimplementedFavouritesServiceServer()
}

func RegisterFavouritesServiceServer(s grpc.ServiceRegistrar, srv FavouritesServiceServer) {
	// If the following call pancis, it indicates UnimplementedFavouritesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FavouritesService_ServiceDesc, srv)
}

func _FavouritesService_ListFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavouritesServiceServer).ListFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavouritesService_ListFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavouritesServiceServer).ListFavourites(ctx, req.(*ListFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavouritesService_AddFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavouritesServiceServer).AddFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavouritesService_AddFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavouritesServiceServer).AddFavourites(ctx, req.(*AddFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavouritesService_DeleteFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavouritesServiceServer).DeleteFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavouritesService_DeleteFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavouritesServiceServer).DeleteFavourites(ctx, req.(*DeleteFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FavouritesService_ServiceDesc is the grpc.ServiceDesc for FavouritesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavouritesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favourites_v1.FavouritesService",
	HandlerType: (*FavouritesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFavourites",
			Handler:    _FavouritesService_ListFavourites_Handler,
		},
		{
			MethodName: "AddFavourites",
			Handler:    _FavouritesService_AddFavourites_Handler,
		},
		{
			MethodName: "DeleteFavourites",
			Handler:    _FavouritesService_DeleteFavourites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "favourites.proto",
}
