// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: user/v1/service.proto

package user

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_v1_service_proto protoreflect.FileDescriptor

const file_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15user/v1/service.proto\x12/github.com.M1steryO.RelocatorEvents.user.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x16user/v1/messages.proto2\xe8\x05\n" +
	"\vUserService\x12\xa5\x01\n" +
	"\x06Create\x12>.github.com.M1steryO.RelocatorEvents.user.api.v1.CreateRequest\x1a?.github.com.M1steryO.RelocatorEvents.user.api.v1.CreateResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/user/v1/create\x12\x92\x01\n" +
	"\x03Get\x12;.github.com.M1steryO.RelocatorEvents.user.api.v1.GetRequest\x1a<.github.com.M1steryO.RelocatorEvents.user.api.v1.GetResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/user/v1\x12\xb0\x01\n" +
	"\x13GetUserByTelegramId\x12K.github.com.M1steryO.RelocatorEvents.user.api.v1.GetUserByTelegramIdRequest\x1aL.github.com.M1steryO.RelocatorEvents.user.api.v1.GetUserByTelegramIdResponse\x12u\n" +
	"\x06Update\x12>.github.com.M1steryO.RelocatorEvents.user.api.v1.UpdateRequest\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r:\x01*2\b/user/v1\x12r\n" +
	"\x06Delete\x12>.github.com.M1steryO.RelocatorEvents.user.api.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	"*\b/user/v1BEZCgithub.com/M1steryO/RelocatorEvents/auth/pkg/api/proto/user/v1;userb\x06proto3"

var file_user_v1_service_proto_goTypes = []any{
	(*CreateRequest)(nil),               // 0: github.com.M1steryO.RelocatorEvents.user.api.v1.CreateRequest
	(*GetRequest)(nil),                  // 1: github.com.M1steryO.RelocatorEvents.user.api.v1.GetRequest
	(*GetUserByTelegramIdRequest)(nil),  // 2: github.com.M1steryO.RelocatorEvents.user.api.v1.GetUserByTelegramIdRequest
	(*UpdateRequest)(nil),               // 3: github.com.M1steryO.RelocatorEvents.user.api.v1.UpdateRequest
	(*DeleteRequest)(nil),               // 4: github.com.M1steryO.RelocatorEvents.user.api.v1.DeleteRequest
	(*CreateResponse)(nil),              // 5: github.com.M1steryO.RelocatorEvents.user.api.v1.CreateResponse
	(*GetResponse)(nil),                 // 6: github.com.M1steryO.RelocatorEvents.user.api.v1.GetResponse
	(*GetUserByTelegramIdResponse)(nil), // 7: github.com.M1steryO.RelocatorEvents.user.api.v1.GetUserByTelegramIdResponse
	(*emptypb.Empty)(nil),               // 8: google.protobuf.Empty
}
var file_user_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Create:input_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.CreateRequest
	1, // 1: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Get:input_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.GetRequest
	2, // 2: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.GetUserByTelegramId:input_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.GetUserByTelegramIdRequest
	3, // 3: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Update:input_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.UpdateRequest
	4, // 4: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Delete:input_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.DeleteRequest
	5, // 5: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Create:output_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.CreateResponse
	6, // 6: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Get:output_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.GetResponse
	7, // 7: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.GetUserByTelegramId:output_type -> github.com.M1steryO.RelocatorEvents.user.api.v1.GetUserByTelegramIdResponse
	8, // 8: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Update:output_type -> google.protobuf.Empty
	8, // 9: github.com.M1steryO.RelocatorEvents.user.api.v1.UserService.Delete:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_service_proto_init() }
func file_user_v1_service_proto_init() {
	if File_user_v1_service_proto != nil {
		return
	}
	file_user_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_service_proto_rawDesc), len(file_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_service_proto_goTypes,
		DependencyIndexes: file_user_v1_service_proto_depIdxs,
	}.Build()
	File_user_v1_service_proto = out.File
	file_user_v1_service_proto_goTypes = nil
	file_user_v1_service_proto_depIdxs = nil
}
