// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: favourites/v1/messages.proto

package favourites

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Link          string                  `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Rating        *wrapperspb.FloatValue  `protobuf:"bytes,5,opt,name=rating,proto3" json:"rating,omitempty"`
	MinAge        *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=min_age,proto3" json:"min_age,omitempty"`
	MinPrice      *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=min_price,proto3" json:"min_price,omitempty"`
	StartsAt      *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=starts_at,proto3" json:"starts_at,omitempty"`
	ImageUrl      *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=image_url,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=created_at,proto3" json:"created_at,omitempty"`
	Currency      *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_favourites_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Event) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Event) GetRating() *wrapperspb.FloatValue {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *Event) GetMinAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinAge
	}
	return nil
}

func (x *Event) GetMinPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinPrice
	}
	return nil
}

func (x *Event) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Event) GetImageUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetCurrency() *wrapperspb.StringValue {
	if x != nil {
		return x.Currency
	}
	return nil
}

type ListFavouritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavouritesRequest) Reset() {
	*x = ListFavouritesRequest{}
	mi := &file_favourites_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavouritesRequest) ProtoMessage() {}

func (x *ListFavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavouritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavouritesRequest) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{1}
}

type ListFavouritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavouritesResponse) Reset() {
	*x = ListFavouritesResponse{}
	mi := &file_favourites_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavouritesResponse) ProtoMessage() {}

func (x *ListFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavouritesResponse.ProtoReflect.Descriptor instead.
func (*ListFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ListFavouritesResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type AddFavouritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavouritesRequest) Reset() {
	*x = AddFavouritesRequest{}
	mi := &file_favourites_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavouritesRequest) ProtoMessage() {}

func (x *AddFavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavouritesRequest.ProtoReflect.Descriptor instead.
func (*AddFavouritesRequest) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AddFavouritesRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type AddFavouritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavouritesResponse) Reset() {
	*x = AddFavouritesResponse{}
	mi := &file_favourites_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavouritesResponse) ProtoMessage() {}

func (x *AddFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavouritesResponse.ProtoReflect.Descriptor instead.
func (*AddFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{4}
}

type DeleteFavouritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavouritesRequest) Reset() {
	*x = DeleteFavouritesRequest{}
	mi := &file_favourites_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouritesRequest) ProtoMessage() {}

func (x *DeleteFavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouritesRequest.ProtoReflect.Descriptor instead.
func (*DeleteFavouritesRequest) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFavouritesRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type DeleteFavouritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavouritesResponse) Reset() {
	*x = DeleteFavouritesResponse{}
	mi := &file_favourites_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavouritesResponse) ProtoMessage() {}

func (x *DeleteFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavouritesResponse.ProtoReflect.Descriptor instead.
func (*DeleteFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_favourites_v1_messages_proto_rawDescGZIP(), []int{6}
}

var File_favourites_v1_messages_proto protoreflect.FileDescriptor

const file_favourites_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1cfavourites/v1/messages.proto\x125github.com.M1steryO.RelocatorEvents.favourites.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x94\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x123\n" +
	"\x06rating\x18\x05 \x01(\v2\x1b.google.protobuf.FloatValueR\x06rating\x125\n" +
	"\amin_age\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\amin_age\x129\n" +
	"\tmin_price\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\tmin_price\x128\n" +
	"\tstarts_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstarts_at\x12:\n" +
	"\timage_url\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\timage_url\x12:\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x128\n" +
	"\bcurrency\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\bcurrency\"\x17\n" +
	"\x15ListFavouritesRequest\"n\n" +
	"\x16ListFavouritesResponse\x12T\n" +
	"\x06events\x18\x01 \x03(\v2<.github.com.M1steryO.RelocatorEvents.favourites.api.v1.EventR\x06events\"1\n" +
	"\x14AddFavouritesRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"\x17\n" +
	"\x15AddFavouritesResponse\"4\n" +
	"\x17DeleteFavouritesRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"\x1a\n" +
	"\x18DeleteFavouritesResponseBSZQgithub.com/M1steryO/RelocatorEvents/events/pkg/api/proto/favourites/v1;favouritesb\x06proto3"

var (
	file_favourites_v1_messages_proto_rawDescOnce sync.Once
	file_favourites_v1_messages_proto_rawDescData []byte
)

func file_favourites_v1_messages_proto_rawDescGZIP() []byte {
	file_favourites_v1_messages_proto_rawDescOnce.Do(func() {
		file_favourites_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_favourites_v1_messages_proto_rawDesc), len(file_favourites_v1_messages_proto_rawDesc)))
	})
	return file_favourites_v1_messages_proto_rawDescData
}

var file_favourites_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_favourites_v1_messages_proto_goTypes = []any{
	(*Event)(nil),                    // 0: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event
	(*ListFavouritesRequest)(nil),    // 1: github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesRequest
	(*ListFavouritesResponse)(nil),   // 2: github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesResponse
	(*AddFavouritesRequest)(nil),     // 3: github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesRequest
	(*AddFavouritesResponse)(nil),    // 4: github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesResponse
	(*DeleteFavouritesRequest)(nil),  // 5: github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesRequest
	(*DeleteFavouritesResponse)(nil), // 6: github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesResponse
	(*wrapperspb.StringValue)(nil),   // 7: google.protobuf.StringValue
	(*wrapperspb.FloatValue)(nil),    // 8: google.protobuf.FloatValue
	(*wrapperspb.Int32Value)(nil),    // 9: google.protobuf.Int32Value
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_favourites_v1_messages_proto_depIdxs = []int32{
	7,  // 0: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.description:type_name -> google.protobuf.StringValue
	8,  // 1: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.rating:type_name -> google.protobuf.FloatValue
	9,  // 2: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.min_age:type_name -> google.protobuf.Int32Value
	9,  // 3: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.min_price:type_name -> google.protobuf.Int32Value
	10, // 4: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.starts_at:type_name -> google.protobuf.Timestamp
	7,  // 5: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.image_url:type_name -> google.protobuf.StringValue
	10, // 6: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.created_at:type_name -> google.protobuf.Timestamp
	7,  // 7: github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event.currency:type_name -> google.protobuf.StringValue
	0,  // 8: github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesResponse.events:type_name -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.Event
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_favourites_v1_messages_proto_init() }
func file_favourites_v1_messages_proto_init() {
	if File_favourites_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_favourites_v1_messages_proto_rawDesc), len(file_favourites_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_favourites_v1_messages_proto_goTypes,
		DependencyIndexes: file_favourites_v1_messages_proto_depIdxs,
		MessageInfos:      file_favourites_v1_messages_proto_msgTypes,
	}.Build()
	File_favourites_v1_messages_proto = out.File
	file_favourites_v1_messages_proto_goTypes = nil
	file_favourites_v1_messages_proto_depIdxs = nil
}
