// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: favourites/v1/service.proto

package favourites

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_favourites_v1_service_proto protoreflect.FileDescriptor

const file_favourites_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bfavourites/v1/service.proto\x125github.com.M1steryO.RelocatorEvents.favourites.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cfavourites/v1/messages.proto2\xfc\x04\n" +
	"\x11FavouritesService\x12\xc5\x01\n" +
	"\x0eListFavourites\x12L.github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesRequest\x1aM.github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/favourites/v1\x12\xc5\x01\n" +
	"\rAddFavourites\x12K.github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesRequest\x1aL.github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/favourites/v1\x12\xd6\x01\n" +
	"\x10DeleteFavourites\x12N.github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesRequest\x1aO.github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/favourites/v1/{event_id}BSZQgithub.com/M1steryO/RelocatorEvents/events/pkg/api/proto/favourites/v1;favouritesb\x06proto3"

var file_favourites_v1_service_proto_goTypes = []any{
	(*ListFavouritesRequest)(nil),    // 0: github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesRequest
	(*AddFavouritesRequest)(nil),     // 1: github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesRequest
	(*DeleteFavouritesRequest)(nil),  // 2: github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesRequest
	(*ListFavouritesResponse)(nil),   // 3: github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesResponse
	(*AddFavouritesResponse)(nil),    // 4: github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesResponse
	(*DeleteFavouritesResponse)(nil), // 5: github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesResponse
}
var file_favourites_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.M1steryO.RelocatorEvents.favourites.api.v1.FavouritesService.ListFavourites:input_type -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesRequest
	1, // 1: github.com.M1steryO.RelocatorEvents.favourites.api.v1.FavouritesService.AddFavourites:input_type -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesRequest
	2, // 2: github.com.M1steryO.RelocatorEvents.favourites.api.v1.FavouritesService.DeleteFavourites:input_type -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesRequest
	3, // 3: github.com.M1steryO.RelocatorEvents.favourites.api.v1.FavouritesService.ListFavourites:output_type -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.ListFavouritesResponse
	4, // 4: github.com.M1steryO.RelocatorEvents.favourites.api.v1.FavouritesService.AddFavourites:output_type -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.AddFavouritesResponse
	5, // 5: github.com.M1steryO.RelocatorEvents.favourites.api.v1.FavouritesService.DeleteFavourites:output_type -> github.com.M1steryO.RelocatorEvents.favourites.api.v1.DeleteFavouritesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_favourites_v1_service_proto_init() }
func file_favourites_v1_service_proto_init() {
	if File_favourites_v1_service_proto != nil {
		return
	}
	file_favourites_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_favourites_v1_service_proto_rawDesc), len(file_favourites_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favourites_v1_service_proto_goTypes,
		DependencyIndexes: file_favourites_v1_service_proto_depIdxs,
	}.Build()
	File_favourites_v1_service_proto = out.File
	file_favourites_v1_service_proto_goTypes = nil
	file_favourites_v1_service_proto_depIdxs = nil
}
