// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/service.proto

package events

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_events_v1_service_proto protoreflect.FileDescriptor

const file_events_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17events/v1/service.proto\x121github.com.M1steryO.RelocatorEvents.events.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18events/v1/messages.proto2\xd3\a\n" +
	"\fEventService\x12\xa2\x01\n" +
	"\bGetEvent\x12=.github.com.M1steryO.RelocatorEvents.events.api.v1.GetRequest\x1a>.github.com.M1steryO.RelocatorEvents.events.api.v1.GetResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/events/v1/{id}\x12\xb2\x01\n" +
	"\n" +
	"ListEvents\x12D.github.com.M1steryO.RelocatorEvents.events.api.v1.ListEventsRequest\x1aE.github.com.M1steryO.RelocatorEvents.events.api.v1.ListEventsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/events/v1/list\x12\xc9\x01\n" +
	"\x0eListFavourites\x12H.github.com.M1steryO.RelocatorEvents.events.api.v1.ListFavouritesRequest\x1aI.github.com.M1steryO.RelocatorEvents.events.api.v1.ListFavouritesResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/events/v1/favourites/list\x12\xc4\x01\n" +
	"\rAddFavourites\x12G.github.com.M1steryO.RelocatorEvents.events.api.v1.AddFavouritesRequest\x1aH.github.com.M1steryO.RelocatorEvents.events.api.v1.AddFavouritesResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/events/v1/favourites\x12\xd5\x01\n" +
	"\x10DeleteFavourites\x12J.github.com.M1steryO.RelocatorEvents.events.api.v1.DeleteFavouritesRequest\x1aK.github.com.M1steryO.RelocatorEvents.events.api.v1.DeleteFavouritesResponse\"(\x82\xd3\xe4\x93\x02\"* /events/v1/favourites/{event_id}BKZIgithub.com/M1steryO/RelocatorEvents/events/pkg/api/proto/events/v1;eventsb\x06proto3"

var file_events_v1_service_proto_goTypes = []any{
	(*GetRequest)(nil),               // 0: github.com.M1steryO.RelocatorEvents.events.api.v1.GetRequest
	(*ListEventsRequest)(nil),        // 1: github.com.M1steryO.RelocatorEvents.events.api.v1.ListEventsRequest
	(*ListFavouritesRequest)(nil),    // 2: github.com.M1steryO.RelocatorEvents.events.api.v1.ListFavouritesRequest
	(*AddFavouritesRequest)(nil),     // 3: github.com.M1steryO.RelocatorEvents.events.api.v1.AddFavouritesRequest
	(*DeleteFavouritesRequest)(nil),  // 4: github.com.M1steryO.RelocatorEvents.events.api.v1.DeleteFavouritesRequest
	(*GetResponse)(nil),              // 5: github.com.M1steryO.RelocatorEvents.events.api.v1.GetResponse
	(*ListEventsResponse)(nil),       // 6: github.com.M1steryO.RelocatorEvents.events.api.v1.ListEventsResponse
	(*ListFavouritesResponse)(nil),   // 7: github.com.M1steryO.RelocatorEvents.events.api.v1.ListFavouritesResponse
	(*AddFavouritesResponse)(nil),    // 8: github.com.M1steryO.RelocatorEvents.events.api.v1.AddFavouritesResponse
	(*DeleteFavouritesResponse)(nil), // 9: github.com.M1steryO.RelocatorEvents.events.api.v1.DeleteFavouritesResponse
}
var file_events_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.GetEvent:input_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.GetRequest
	1, // 1: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.ListEvents:input_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.ListEventsRequest
	2, // 2: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.ListFavourites:input_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.ListFavouritesRequest
	3, // 3: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.AddFavourites:input_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.AddFavouritesRequest
	4, // 4: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.DeleteFavourites:input_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.DeleteFavouritesRequest
	5, // 5: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.GetEvent:output_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.GetResponse
	6, // 6: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.ListEvents:output_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.ListEventsResponse
	7, // 7: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.ListFavourites:output_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.ListFavouritesResponse
	8, // 8: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.AddFavourites:output_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.AddFavouritesResponse
	9, // 9: github.com.M1steryO.RelocatorEvents.events.api.v1.EventService.DeleteFavourites:output_type -> github.com.M1steryO.RelocatorEvents.events.api.v1.DeleteFavouritesResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_service_proto_init() }
func file_events_v1_service_proto_init() {
	if File_events_v1_service_proto != nil {
		return
	}
	file_events_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_service_proto_rawDesc), len(file_events_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_v1_service_proto_goTypes,
		DependencyIndexes: file_events_v1_service_proto_depIdxs,
	}.Build()
	File_events_v1_service_proto = out.File
	file_events_v1_service_proto_goTypes = nil
	file_events_v1_service_proto_depIdxs = nil
}
