syntax = "proto3";

package github.com.M1steryO.RelocatorEvents.user.api.v1;
option go_package = "github.com/M1steryO/RelocatorEvents/users/pkg/api/proto/user/v1;user";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "user/v1/messages.proto";



service UserService {
  rpc Create(CreateRequest) returns (CreateResponse){
    option (google.api.http) = {
      post: "/user/v1/create"
      body: "*"
    };
  };
  rpc Get(GetRequest) returns (GetResponse){
    option (google.api.http) = {
      get: "/user/v1"
    };
  };
  rpc GetUserByTelegramId(GetUserByTelegramIdRequest) returns (GetUserByTelegramIdResponse);
  rpc GetUserByEmail(GetUserByEmailRequest) returns (GetUserByEmailResponse);

  rpc Update(UpdateRequest) returns (google.protobuf.Empty){
    option (google.api.http) = {
      patch: "/user/v1"
      body: "*"
    };
  };
  rpc UpdatePassword(UpdatePasswordRequest) returns (google.protobuf.Empty){
    option (google.api.http) = {
      patch: "/user/v1/password"
      body: "*"
    };
  };

  rpc Delete(DeleteRequest) returns (google.protobuf.Empty){
    option (google.api.http) = {
      delete: "/user/v1"
    };
  };
}
