// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reviews/v1/messages.proto

package reviews

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNKNOWN MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE   MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO   MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNKNOWN",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNKNOWN": 0,
		"MEDIA_TYPE_IMAGE":   1,
		"MEDIA_TYPE_VIDEO":   2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_reviews_v1_messages_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_reviews_v1_messages_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{0}
}

type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_reviews_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ListReviewsRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Rating        float32                `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewsCount  int32                  `protobuf:"varint,3,opt,name=reviews_count,proto3" json:"reviews_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_reviews_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *ListReviewsResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ListReviewsResponse) GetReviewsCount() int32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

type MediaAttachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string storage_key = 1 [(validate.rules).string.uri = true];
	StorageKey    string    `protobuf:"bytes,1,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	Type          MediaType `protobuf:"varint,2,opt,name=type,proto3,enum=github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAttachment) Reset() {
	*x = MediaAttachment{}
	mi := &file_reviews_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAttachment) ProtoMessage() {}

func (x *MediaAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAttachment.ProtoReflect.Descriptor instead.
func (*MediaAttachment) Descriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MediaAttachment) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *MediaAttachment) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNKNOWN
}

type Review struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Grade         int32                   `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Advantages    string                  `protobuf:"bytes,2,opt,name=advantages,proto3" json:"advantages,omitempty"`
	Disadvantages string                  `protobuf:"bytes,3,opt,name=disadvantages,proto3" json:"disadvantages,omitempty"`
	Text          string                  `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Media         []*MediaAttachment      `protobuf:"bytes,5,rep,name=media,proto3" json:"media,omitempty"`
	AuthorId      int64                   `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AuthorName    *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_reviews_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Review) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Review) GetAdvantages() string {
	if x != nil {
		return x.Advantages
	}
	return ""
}

func (x *Review) GetDisadvantages() string {
	if x != nil {
		return x.Disadvantages
	}
	return ""
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Review) GetMedia() []*MediaAttachment {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Review) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Review) GetAuthorName() *wrapperspb.StringValue {
	if x != nil {
		return x.AuthorName
	}
	return nil
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Review        *Review                `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_reviews_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReviewRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_reviews_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_reviews_v1_messages_proto_rawDescGZIP(), []int{5}
}

var File_reviews_v1_messages_proto protoreflect.FileDescriptor

const file_reviews_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x19reviews/v1/messages.proto\x122github.com.M1steryO.RelocatorEvents.reviews.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"8\n" +
	"\x12ListReviewsRequest\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\"\xa9\x01\n" +
	"\x13ListReviewsResponse\x12T\n" +
	"\areviews\x18\x01 \x03(\v2:.github.com.M1steryO.RelocatorEvents.reviews.api.v1.ReviewR\areviews\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x02R\x06rating\x12$\n" +
	"\rreviews_count\x18\x03 \x01(\x05R\rreviews_count\"\x8f\x01\n" +
	"\x0fMediaAttachment\x12\x1f\n" +
	"\vstorage_key\x18\x01 \x01(\tR\n" +
	"storageKey\x12[\n" +
	"\x04type\x18\x02 \x01(\x0e2=.github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\"\x9b\x03\n" +
	"\x06Review\x12\x1f\n" +
	"\x05grade\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\n" +
	"(\x00R\x05grade\x12'\n" +
	"\n" +
	"advantages\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\n" +
	"advantages\x12-\n" +
	"\rdisadvantages\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18dR\rdisadvantages\x12\x1c\n" +
	"\x04text\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\xc8\x01R\x04text\x12c\n" +
	"\x05media\x18\x05 \x03(\v2C.github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaAttachmentB\b\xfaB\x05\x92\x01\x02\x10\x03R\x05media\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\vauthor_name\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"authorName\"\x97\x01\n" +
	"\x13CreateReviewRequest\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\x12\\\n" +
	"\x06review\x18\x02 \x01(\v2:.github.com.M1steryO.RelocatorEvents.reviews.api.v1.ReviewB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06review\"\x16\n" +
	"\x14CreateReviewResponse*O\n" +
	"\tMediaType\x12\x16\n" +
	"\x12MEDIA_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02BMZKgithub.com/M1steryO/RelocatorEvents/events/pkg/api/proto/reviews/v1;reviewsb\x06proto3"

var (
	file_reviews_v1_messages_proto_rawDescOnce sync.Once
	file_reviews_v1_messages_proto_rawDescData []byte
)

func file_reviews_v1_messages_proto_rawDescGZIP() []byte {
	file_reviews_v1_messages_proto_rawDescOnce.Do(func() {
		file_reviews_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviews_v1_messages_proto_rawDesc), len(file_reviews_v1_messages_proto_rawDesc)))
	})
	return file_reviews_v1_messages_proto_rawDescData
}

var file_reviews_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reviews_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reviews_v1_messages_proto_goTypes = []any{
	(MediaType)(0),                 // 0: github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaType
	(*ListReviewsRequest)(nil),     // 1: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsRequest
	(*ListReviewsResponse)(nil),    // 2: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsResponse
	(*MediaAttachment)(nil),        // 3: github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaAttachment
	(*Review)(nil),                 // 4: github.com.M1steryO.RelocatorEvents.reviews.api.v1.Review
	(*CreateReviewRequest)(nil),    // 5: github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewRequest
	(*CreateReviewResponse)(nil),   // 6: github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 8: google.protobuf.StringValue
}
var file_reviews_v1_messages_proto_depIdxs = []int32{
	4, // 0: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsResponse.reviews:type_name -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.Review
	0, // 1: github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaAttachment.type:type_name -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaType
	3, // 2: github.com.M1steryO.RelocatorEvents.reviews.api.v1.Review.media:type_name -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.MediaAttachment
	7, // 3: github.com.M1steryO.RelocatorEvents.reviews.api.v1.Review.created_at:type_name -> google.protobuf.Timestamp
	8, // 4: github.com.M1steryO.RelocatorEvents.reviews.api.v1.Review.author_name:type_name -> google.protobuf.StringValue
	4, // 5: github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewRequest.review:type_name -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.Review
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_reviews_v1_messages_proto_init() }
func file_reviews_v1_messages_proto_init() {
	if File_reviews_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviews_v1_messages_proto_rawDesc), len(file_reviews_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reviews_v1_messages_proto_goTypes,
		DependencyIndexes: file_reviews_v1_messages_proto_depIdxs,
		EnumInfos:         file_reviews_v1_messages_proto_enumTypes,
		MessageInfos:      file_reviews_v1_messages_proto_msgTypes,
	}.Build()
	File_reviews_v1_messages_proto = out.File
	file_reviews_v1_messages_proto_goTypes = nil
	file_reviews_v1_messages_proto_depIdxs = nil
}
