// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reviews/v1/service.proto

package reviews

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_reviews_v1_service_proto protoreflect.FileDescriptor

const file_reviews_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18reviews/v1/service.proto\x122github.com.M1steryO.RelocatorEvents.reviews.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19reviews/v1/messages.proto2\x82\x03\n" +
	"\x0eReviewsService\x12\xb3\x01\n" +
	"\vListReviews\x12F.github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsRequest\x1aG.github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/reviews/v1\x12\xb9\x01\n" +
	"\fCreateReview\x12G.github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewRequest\x1aH.github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/reviews/v1BMZKgithub.com/M1steryO/RelocatorEvents/events/pkg/api/proto/reviews/v1;reviewsb\x06proto3"

var file_reviews_v1_service_proto_goTypes = []any{
	(*ListReviewsRequest)(nil),   // 0: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsRequest
	(*CreateReviewRequest)(nil),  // 1: github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewRequest
	(*ListReviewsResponse)(nil),  // 2: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsResponse
	(*CreateReviewResponse)(nil), // 3: github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewResponse
}
var file_reviews_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ReviewsService.ListReviews:input_type -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsRequest
	1, // 1: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ReviewsService.CreateReview:input_type -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewRequest
	2, // 2: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ReviewsService.ListReviews:output_type -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.ListReviewsResponse
	3, // 3: github.com.M1steryO.RelocatorEvents.reviews.api.v1.ReviewsService.CreateReview:output_type -> github.com.M1steryO.RelocatorEvents.reviews.api.v1.CreateReviewResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reviews_v1_service_proto_init() }
func file_reviews_v1_service_proto_init() {
	if File_reviews_v1_service_proto != nil {
		return
	}
	file_reviews_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviews_v1_service_proto_rawDesc), len(file_reviews_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reviews_v1_service_proto_goTypes,
		DependencyIndexes: file_reviews_v1_service_proto_depIdxs,
	}.Build()
	File_reviews_v1_service_proto = out.File
	file_reviews_v1_service_proto_goTypes = nil
	file_reviews_v1_service_proto_depIdxs = nil
}
