// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: auth/v1/service.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_service_proto protoreflect.FileDescriptor

const file_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/service.proto\x12/github.com.M1steryO.RelocatorEvents.auth.api.v1\x1a\x16auth/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto2\xd1\x06\n" +
	"\vAuthService\x12\x86\x01\n" +
	"\x05Login\x12=.github.com.M1steryO.RelocatorEvents.auth.api.v1.LoginRequest\x1a>.github.com.M1steryO.RelocatorEvents.auth.api.v1.LoginResponse\x12\x9d\x01\n" +
	"\rTelegramLogin\x12E.github.com.M1steryO.RelocatorEvents.auth.api.v1.TelegramLoginRequest\x1aE.github.com.M1steryO.RelocatorEvents.auth.api.v1.TelegramLoginReponse\x12\x86\x01\n" +
	"\x05Check\x12=.github.com.M1steryO.RelocatorEvents.auth.api.v1.CheckRequest\x1a>.github.com.M1steryO.RelocatorEvents.auth.api.v1.CheckResponse\x12\xc8\x01\n" +
	"\x0fGetRefreshToken\x12G.github.com.M1steryO.RelocatorEvents.auth.api.v1.GetRefreshTokenRequest\x1aH.github.com.M1steryO.RelocatorEvents.auth.api.v1.GetRefreshTokenResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/auth/v1/get-refresh-token\x12\xc4\x01\n" +
	"\x0eGetAccessToken\x12F.github.com.M1steryO.RelocatorEvents.auth.api.v1.GetAccessTokenRequest\x1aG.github.com.M1steryO.RelocatorEvents.auth.api.v1.GetAccessTokenResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/auth/v1/get-access-tokenBEZCgithub.com/M1steryO/RelocatorEvents/auth/pkg/api/proto/auth/v1;authb\x06proto3"

var file_auth_v1_service_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: github.com.M1steryO.RelocatorEvents.auth.api.v1.LoginRequest
	(*TelegramLoginRequest)(nil),    // 1: github.com.M1steryO.RelocatorEvents.auth.api.v1.TelegramLoginRequest
	(*CheckRequest)(nil),            // 2: github.com.M1steryO.RelocatorEvents.auth.api.v1.CheckRequest
	(*GetRefreshTokenRequest)(nil),  // 3: github.com.M1steryO.RelocatorEvents.auth.api.v1.GetRefreshTokenRequest
	(*GetAccessTokenRequest)(nil),   // 4: github.com.M1steryO.RelocatorEvents.auth.api.v1.GetAccessTokenRequest
	(*LoginResponse)(nil),           // 5: github.com.M1steryO.RelocatorEvents.auth.api.v1.LoginResponse
	(*TelegramLoginReponse)(nil),    // 6: github.com.M1steryO.RelocatorEvents.auth.api.v1.TelegramLoginReponse
	(*CheckResponse)(nil),           // 7: github.com.M1steryO.RelocatorEvents.auth.api.v1.CheckResponse
	(*GetRefreshTokenResponse)(nil), // 8: github.com.M1steryO.RelocatorEvents.auth.api.v1.GetRefreshTokenResponse
	(*GetAccessTokenResponse)(nil),  // 9: github.com.M1steryO.RelocatorEvents.auth.api.v1.GetAccessTokenResponse
}
var file_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.Login:input_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.LoginRequest
	1, // 1: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.TelegramLogin:input_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.TelegramLoginRequest
	2, // 2: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.Check:input_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.CheckRequest
	3, // 3: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.GetRefreshToken:input_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.GetRefreshTokenRequest
	4, // 4: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.GetAccessToken:input_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.GetAccessTokenRequest
	5, // 5: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.Login:output_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.LoginResponse
	6, // 6: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.TelegramLogin:output_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.TelegramLoginReponse
	7, // 7: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.Check:output_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.CheckResponse
	8, // 8: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.GetRefreshToken:output_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.GetRefreshTokenResponse
	9, // 9: github.com.M1steryO.RelocatorEvents.auth.api.v1.AuthService.GetAccessToken:output_type -> github.com.M1steryO.RelocatorEvents.auth.api.v1.GetAccessTokenResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_service_proto_init() }
func file_auth_v1_service_proto_init() {
	if File_auth_v1_service_proto != nil {
		return
	}
	file_auth_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_proto_depIdxs,
	}.Build()
	File_auth_v1_service_proto = out.File
	file_auth_v1_service_proto_goTypes = nil
	file_auth_v1_service_proto_depIdxs = nil
}
