// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: reviews.proto

package reviews_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListReviewsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReviewsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReviewsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReviewsRequestMultiError, or nil if none found.
func (m *ListReviewsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReviewsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := ListReviewsRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListReviewsRequestMultiError(errors)
	}

	return nil
}

// ListReviewsRequestMultiError is an error wrapping multiple validation errors
// returned by ListReviewsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListReviewsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReviewsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReviewsRequestMultiError) AllErrors() []error { return m }

// ListReviewsRequestValidationError is the validation error returned by
// ListReviewsRequest.Validate if the designated constraints aren't met.
type ListReviewsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReviewsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReviewsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReviewsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReviewsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReviewsRequestValidationError) ErrorName() string {
	return "ListReviewsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListReviewsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReviewsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReviewsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReviewsRequestValidationError{}

// Validate checks the field values on ListReviewsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReviewsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReviewsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReviewsResponseMultiError, or nil if none found.
func (m *ListReviewsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReviewsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReviews() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReviewsResponseValidationError{
						field:  fmt.Sprintf("Reviews[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReviewsResponseValidationError{
						field:  fmt.Sprintf("Reviews[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReviewsResponseValidationError{
					field:  fmt.Sprintf("Reviews[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListReviewsResponseMultiError(errors)
	}

	return nil
}

// ListReviewsResponseMultiError is an error wrapping multiple validation
// errors returned by ListReviewsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListReviewsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReviewsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReviewsResponseMultiError) AllErrors() []error { return m }

// ListReviewsResponseValidationError is the validation error returned by
// ListReviewsResponse.Validate if the designated constraints aren't met.
type ListReviewsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReviewsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReviewsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReviewsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReviewsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReviewsResponseValidationError) ErrorName() string {
	return "ListReviewsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListReviewsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReviewsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReviewsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReviewsResponseValidationError{}

// Validate checks the field values on MediaAttachment with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MediaAttachment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MediaAttachment with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MediaAttachmentMultiError, or nil if none found.
func (m *MediaAttachment) ValidateAll() error {
	return m.validate(true)
}

func (m *MediaAttachment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StorageKey

	if _, ok := MediaType_name[int32(m.GetType())]; !ok {
		err := MediaAttachmentValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return MediaAttachmentMultiError(errors)
	}

	return nil
}

// MediaAttachmentMultiError is an error wrapping multiple validation errors
// returned by MediaAttachment.ValidateAll() if the designated constraints
// aren't met.
type MediaAttachmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MediaAttachmentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MediaAttachmentMultiError) AllErrors() []error { return m }

// MediaAttachmentValidationError is the validation error returned by
// MediaAttachment.Validate if the designated constraints aren't met.
type MediaAttachmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MediaAttachmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MediaAttachmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MediaAttachmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MediaAttachmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MediaAttachmentValidationError) ErrorName() string { return "MediaAttachmentValidationError" }

// Error satisfies the builtin error interface
func (e MediaAttachmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMediaAttachment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MediaAttachmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MediaAttachmentValidationError{}

// Validate checks the field values on Review with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Review) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Review with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ReviewMultiError, or nil if none found.
func (m *Review) ValidateAll() error {
	return m.validate(true)
}

func (m *Review) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetGrade(); val < 0 || val > 10 {
		err := ReviewValidationError{
			field:  "Grade",
			reason: "value must be inside range [0, 10]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAdvantages()) > 200 {
		err := ReviewValidationError{
			field:  "Advantages",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDisadvantages()) > 200 {
		err := ReviewValidationError{
			field:  "Disadvantages",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetText()); l < 1 || l > 200 {
		err := ReviewValidationError{
			field:  "Text",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetMedia()) > 3 {
		err := ReviewValidationError{
			field:  "Media",
			reason: "value must contain no more than 3 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetMedia() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ReviewValidationError{
						field:  fmt.Sprintf("Media[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ReviewValidationError{
						field:  fmt.Sprintf("Media[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ReviewValidationError{
					field:  fmt.Sprintf("Media[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for AuthorId

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReviewValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReviewValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReviewValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReviewMultiError(errors)
	}

	return nil
}

// ReviewMultiError is an error wrapping multiple validation errors returned by
// Review.ValidateAll() if the designated constraints aren't met.
type ReviewMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReviewMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReviewMultiError) AllErrors() []error { return m }

// ReviewValidationError is the validation error returned by Review.Validate if
// the designated constraints aren't met.
type ReviewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReviewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReviewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReviewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReviewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReviewValidationError) ErrorName() string { return "ReviewValidationError" }

// Error satisfies the builtin error interface
func (e ReviewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReview.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReviewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReviewValidationError{}

// Validate checks the field values on CreateReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReviewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReviewRequestMultiError, or nil if none found.
func (m *CreateReviewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReviewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := CreateReviewRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetReview() == nil {
		err := CreateReviewRequestValidationError{
			field:  "Review",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetReview()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateReviewRequestValidationError{
					field:  "Review",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateReviewRequestValidationError{
					field:  "Review",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReview()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateReviewRequestValidationError{
				field:  "Review",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateReviewRequestMultiError(errors)
	}

	return nil
}

// CreateReviewRequestMultiError is an error wrapping multiple validation
// errors returned by CreateReviewRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateReviewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReviewRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReviewRequestMultiError) AllErrors() []error { return m }

// CreateReviewRequestValidationError is the validation error returned by
// CreateReviewRequest.Validate if the designated constraints aren't met.
type CreateReviewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReviewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReviewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReviewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReviewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReviewRequestValidationError) ErrorName() string {
	return "CreateReviewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReviewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReviewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReviewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReviewRequestValidationError{}

// Validate checks the field values on CreateReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReviewResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReviewResponseMultiError, or nil if none found.
func (m *CreateReviewResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReviewResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateReviewResponseMultiError(errors)
	}

	return nil
}

// CreateReviewResponseMultiError is an error wrapping multiple validation
// errors returned by CreateReviewResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateReviewResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReviewResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReviewResponseMultiError) AllErrors() []error { return m }

// CreateReviewResponseValidationError is the validation error returned by
// CreateReviewResponse.Validate if the designated constraints aren't met.
type CreateReviewResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReviewResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReviewResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReviewResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReviewResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReviewResponseValidationError) ErrorName() string {
	return "CreateReviewResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReviewResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReviewResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReviewResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReviewResponseValidationError{}
