// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: reviews.proto

package reviews_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNKNOWN MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE   MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO   MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNKNOWN",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNKNOWN": 0,
		"MEDIA_TYPE_IMAGE":   1,
		"MEDIA_TYPE_VIDEO":   2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_reviews_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_reviews_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{0}
}

type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_reviews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{0}
}

func (x *ListReviewsRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_reviews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{1}
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type MediaAttachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string storage_key = 1 [(validate.rules).string.uri = true];
	StorageKey    string    `protobuf:"bytes,1,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	Type          MediaType `protobuf:"varint,2,opt,name=type,proto3,enum=reviews_v1.MediaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAttachment) Reset() {
	*x = MediaAttachment{}
	mi := &file_reviews_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAttachment) ProtoMessage() {}

func (x *MediaAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAttachment.ProtoReflect.Descriptor instead.
func (*MediaAttachment) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{2}
}

func (x *MediaAttachment) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *MediaAttachment) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNKNOWN
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         int32                  `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Advantages    string                 `protobuf:"bytes,2,opt,name=advantages,proto3" json:"advantages,omitempty"`
	Disadvantages string                 `protobuf:"bytes,3,opt,name=disadvantages,proto3" json:"disadvantages,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Media         []*MediaAttachment     `protobuf:"bytes,5,rep,name=media,proto3" json:"media,omitempty"`
	AuthorId      int64                  `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_reviews_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{3}
}

func (x *Review) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Review) GetAdvantages() string {
	if x != nil {
		return x.Advantages
	}
	return ""
}

func (x *Review) GetDisadvantages() string {
	if x != nil {
		return x.Disadvantages
	}
	return ""
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Review) GetMedia() []*MediaAttachment {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Review) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Review        *Review                `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_reviews_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReviewRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_reviews_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{5}
}

var File_reviews_proto protoreflect.FileDescriptor

const file_reviews_proto_rawDesc = "" +
	"\n" +
	"\rreviews.proto\x12\n" +
	"reviews_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x12ListReviewsRequest\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\"C\n" +
	"\x13ListReviewsResponse\x12,\n" +
	"\areviews\x18\x01 \x03(\v2\x12.reviews_v1.ReviewR\areviews\"g\n" +
	"\x0fMediaAttachment\x12\x1f\n" +
	"\vstorage_key\x18\x01 \x01(\tR\n" +
	"storageKey\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.reviews_v1.MediaTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\"\xb8\x02\n" +
	"\x06Review\x12\x1f\n" +
	"\x05grade\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\n" +
	"(\x00R\x05grade\x12(\n" +
	"\n" +
	"advantages\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xc8\x01R\n" +
	"advantages\x12.\n" +
	"\rdisadvantages\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xc8\x01R\rdisadvantages\x12\x1e\n" +
	"\x04text\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x04text\x12;\n" +
	"\x05media\x18\x05 \x03(\v2\x1b.reviews_v1.MediaAttachmentB\b\xfaB\x05\x92\x01\x02\x10\x03R\x05media\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"o\n" +
	"\x13CreateReviewRequest\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\x124\n" +
	"\x06review\x18\x02 \x01(\v2\x12.reviews_v1.ReviewB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06review\"\x16\n" +
	"\x14CreateReviewResponse*O\n" +
	"\tMediaType\x12\x16\n" +
	"\x12MEDIA_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x022\xdc\x01\n" +
	"\n" +
	"Reviews_v1\x12c\n" +
	"\vListReviews\x12\x1e.reviews_v1.ListReviewsRequest\x1a\x1f.reviews_v1.ListReviewsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/reviews/v1\x12i\n" +
	"\fCreateReview\x12\x1f.reviews_v1.CreateReviewRequest\x1a .reviews_v1.CreateReviewResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/reviews/v1BAZ?GolandProjects/RelocatorEvents/events/pkg/reviews_v1;reviews_v1b\x06proto3"

var (
	file_reviews_proto_rawDescOnce sync.Once
	file_reviews_proto_rawDescData []byte
)

func file_reviews_proto_rawDescGZIP() []byte {
	file_reviews_proto_rawDescOnce.Do(func() {
		file_reviews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviews_proto_rawDesc), len(file_reviews_proto_rawDesc)))
	})
	return file_reviews_proto_rawDescData
}

var file_reviews_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reviews_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reviews_proto_goTypes = []any{
	(MediaType)(0),                // 0: reviews_v1.MediaType
	(*ListReviewsRequest)(nil),    // 1: reviews_v1.ListReviewsRequest
	(*ListReviewsResponse)(nil),   // 2: reviews_v1.ListReviewsResponse
	(*MediaAttachment)(nil),       // 3: reviews_v1.MediaAttachment
	(*Review)(nil),                // 4: reviews_v1.Review
	(*CreateReviewRequest)(nil),   // 5: reviews_v1.CreateReviewRequest
	(*CreateReviewResponse)(nil),  // 6: reviews_v1.CreateReviewResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_reviews_proto_depIdxs = []int32{
	4, // 0: reviews_v1.ListReviewsResponse.reviews:type_name -> reviews_v1.Review
	0, // 1: reviews_v1.MediaAttachment.type:type_name -> reviews_v1.MediaType
	3, // 2: reviews_v1.Review.media:type_name -> reviews_v1.MediaAttachment
	7, // 3: reviews_v1.Review.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: reviews_v1.CreateReviewRequest.review:type_name -> reviews_v1.Review
	1, // 5: reviews_v1.Reviews_v1.ListReviews:input_type -> reviews_v1.ListReviewsRequest
	5, // 6: reviews_v1.Reviews_v1.CreateReview:input_type -> reviews_v1.CreateReviewRequest
	2, // 7: reviews_v1.Reviews_v1.ListReviews:output_type -> reviews_v1.ListReviewsResponse
	6, // 8: reviews_v1.Reviews_v1.CreateReview:output_type -> reviews_v1.CreateReviewResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_reviews_proto_init() }
func file_reviews_proto_init() {
	if File_reviews_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviews_proto_rawDesc), len(file_reviews_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reviews_proto_goTypes,
		DependencyIndexes: file_reviews_proto_depIdxs,
		EnumInfos:         file_reviews_proto_enumTypes,
		MessageInfos:      file_reviews_proto_msgTypes,
	}.Build()
	File_reviews_proto = out.File
	file_reviews_proto_goTypes = nil
	file_reviews_proto_depIdxs = nil
}
